model_name: "ltx_lora"
id_token: "freeze time, camera orbit left,"
# data_root: "/media/eisneim/4T/ltx_data"
precomputed_datasets:
  -
    - "/media/eisneim/4T/ltx_data_49_blured/game_p7_49x1024x576"
    - "/media/eisneim/4T/ltx_optical_flow/game_p7_flow_49x1024x576"
  - 
    - "/media/eisneim/4T/ltx_data_121_blured/game_p8_121x512x288"
    - "/media/eisneim/4T/ltx_optical_flow/game_p8_flow_121x512x288"
  -
    - "/media/eisneim/4T/ltx_data_49_blured/game_p8_49x1024x576"
    - "/media/eisneim/4T/ltx_optical_flow/game_p8_flow_49x1024x576"
  - 
    - "/media/eisneim/4T/ltx_data_121_blured/game_p9_121x512x288"
    - "/media/eisneim/4T/ltx_optical_flow/game_p9_flow_121x512x288"
  -
    - "/media/eisneim/4T/ltx_data_49_blured/game_p9_49x1024x576"
    - "/media/eisneim/4T/ltx_optical_flow/game_p9_flow_49x1024x576"
  -
    - "/media/eisneim/4T/ltx_data_121_blured/3dgs_game_1-6_121x512x288"
    - "/media/eisneim/4T/ltx_optical_flow/game-p1-5_blur_flow_121x512x288"
  -
    - "/media/eisneim/4T/ltx_data_201_832x480/game_p7_fliped_201x832x480"
    - "/media/eisneim/4T/ltx_optical_flow/game_p7_fliped_flow_201x832x480"
  -
    - "/media/eisneim/4T/ltx_data_201_832x480/game_p13_fliped_201x832x480"
    - "/media/eisneim/4T/ltx_optical_flow/game_p13_fliped_flow_201x832x480"
  -
    - "/media/eisneim/4T/ltx_data_201_832x480/game_p12_201x832x480"
    - "/media/eisneim/4T/ltx_optical_flow/game_p12_blur_flow_201x832x480"
  -
    - "/media/eisneim/4T/ltx_data_201_832x480/game_p12_fliped_201x832x480"
    - "/media/eisneim/4T/ltx_optical_flow/game_p12_fliped_flow_201x832x480"
  -
    - "/media/eisneim/4T/ltx_data_201_832x480/game_p13_201x832x480"
    - "/media/eisneim/4T/ltx_optical_flow/game_p13_blur_flow_201x832x480"
  -
    - "/media/eisneim/4T/ltx_data_201x512x288/game_p11_201x512x288"
    - "/media/eisneim/4T/ltx_optical_flow/game_p11_flow_201x512x288"
  -
    - "/media/eisneim/4T/ltx_data_49_blured/game_p10_blured_49x1024x576"
    - "/media/eisneim/4T/ltx_optical_flow/game_p10_flow_49x1024x576"
  -
    - "/media/eisneim/4T/ltx_data_49_blured/3dgs_game_1-6_49x1024x576"
    - "/media/eisneim/4T/ltx_optical_flow/game_p1-5_blur_flow_49x1024x576"
  # -
  #   - ""
  #   - ""
  # -
  #   - ""
  #   - ""

output_dir: "/home/eisneim/www/ml/_video_gen/ltx_training/data_flow/flow_assist"
# output_dir: "/home/eisneim/www/ml/_video_gen/ltx_training/data/mixed"
caption_dropout_p: 0.1
caption_dropout_technique: "zero"
dataloader_num_workers: 4
# pretrained_model_name_or_path: "./data/fused"
pretrained_model_name_or_path: "a-r-r-o-w/LTX-Video-0.9.1-diffusers"
prev_checkpoint: "/home/eisneim/www/ml/_video_gen/ltx_training/data_flow/flow_assist/prev-v3-10k"

flow_resolution_shifting: True
seed: 7136
# mixed_precision: "no"
# batch_size: 4
mixed_precision: bf16
# mixed_precision: fp16
batch_size: 3
# train_steps: 3000
train_epochs: 100
# ------- frame shuffle training method -----
enable_frame_shuffle: True
shuffle_ratio: 0.3
shuffle_prob: 0.9

# ----------- lora or full ---
is_i2v: True
noise_to_first_frame: 0.9
train_type: "lora"
rank: 256
lora_alpha: 256
# target_modules: to_q to_k to_v to_out.0
target_modules: "all-linear"
gradient_accumulation_steps: 1
gradient_checkpointing: True

checkpointing_steps: 1000
checkpointing_limit: 4
enable_slicing: True
enable_tiling: True

optimizer_8bit: True
# optimizer_torchao: True
optimizer: adamw
lr: 3e-5
lr_scheduler: constant_with_warmup
lr_warmup_steps: 100
lr_num_cycles: 1
beta1: 0.9
beta2: 0.95
weight_decay: 1e-4
epsilon: 1e-8
max_grad_norm: 1.0

validation_prompts: ""
num_validation_videos: 1
validation_steps: 100000000000000000

tracker_name: ltx_trainer
nccl_timeout: 1800






